-- ============================================================
-- NIS2 / ACN  -  Export CSV del profilo per TUTTE le organizzazioni
-- Variante: separatore ';'  -  codifica WIN1252
-- ============================================================
--
-- ESECUZIONE (un solo comando, dalla cartella del progetto):
--   psql -U postgres -d nis2db -f nis2_export_csv_excel.sql
--
-- Note:
--   * NON serve l'opzione -v ORG_ID: l'id e' gia' scritto in ogni query.
--   * I file .csv vengono creati nella cartella da cui si lancia psql.
--   * Vincolo psql: ogni comando \copy deve stare su UNA riga. La
--     leggibilita' e' data dai commenti e dalla suddivisione in sezioni.
--   * Codifica WIN1252 + separatore ';': i CSV si aprono col doppio clic in Excel (IT).
--
-- ============================================================
-- INDICE DELLE 13 ESTRAZIONI (prodotte per ogni organizzazione)
-- ============================================================
--   01  anagrafica                       Anagrafica del soggetto NIS2 e referente ACN principale
--   02  referenti                        Elenco dei referenti e contatti dell'organizzazione
--   03  asset_critici                    Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
--   04  servizi                          Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
--   05  dipendenze                       Dipendenze dalla catena di fornitura con contratto, SLA e stato
--   06  misure_sicurezza                 Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
--   07  dashboard                        Quadro riepilogativo: contatori chiave dell'organizzazione
--   08  alert_scadenze                   Contratti scaduti o in scadenza entro 180 giorni, con priorita'
--   09  gap_asset_senza_proprietario     Asset critici/importanti privi di proprietario assegnato
--   10  gap_misure                       Misure non ancora implementate (pianificate o in corso)
--   11  storico_modifiche                Storico delle modifiche agli asset (audit trail)
--   12  profilo_target_attuale           Profilo target e profilo attuale per Subcategory (FNCSDP)
--   13  gap_analysis                     Gap analysis: divario target/attuale ordinato per priorita'
--
-- Piu' due file riepilogativi comuni: acn_dashboard_multiorg.csv e
-- acn_gap_dashboard_multiorg.csv
--
-- ORGANIZZAZIONI ESPORTATE:
--   org 1 = Alfa Energia S.p.A.      (Energia)
--   org 2 = BetaCloud S.r.l.         (Infrastrutture digitali)
--   org 3 = Ospedale Regionale Nord  (Sanita')
--   org 4 = TransLogistica S.p.A.    (Trasporti)
--   org 5 = BancaMetro S.p.A.        (Bancario)
-- ============================================================

\encoding WIN1252


-- ============================================================
--  ORGANIZZAZIONE 1 :  Alfa Energia S.p.A.  -  settore Energia
-- ============================================================
\echo ''
\echo '>>> Export organizzazione 1 - Alfa Energia S.p.A.'

-- 01  Anagrafica del soggetto NIS2 e referente ACN principale
\copy (SELECT o.nome AS organizzazione, o.codice_fiscale, o.settore_nis2, o.categoria_nis2, o.pec, o.sito_web, TO_CHAR(o.data_registrazione_acn,'DD/MM/YYYY') AS data_registrazione_acn, (pr.cognome || ' ' || pr.nome) AS referente_acn_principale, pr.email AS email_referente_acn, pr.telefono AS tel_referente_acn, pr.ruolo_organizzativo AS ruolo_referente_acn, CASE WHEN o.attiva THEN 'Attiva' ELSE 'Inattiva' END AS stato FROM organizzazione o LEFT JOIN persona pr ON pr.organizzazione_id = o.id AND pr.is_referente_acn = TRUE WHERE o.id = 1) TO 'acn_org1_01_anagrafica.csv' WITH CSV HEADER DELIMITER ';'

-- 02  Elenco dei referenti e contatti dell'organizzazione
\copy (SELECT (p.cognome || ' ' || p.nome) AS nominativo, p.email, p.telefono, p.ruolo_organizzativo AS ruolo, CASE WHEN p.is_referente_acn THEN 'Si' ELSE 'No' END AS referente_acn_ufficiale, o.nome AS organizzazione, o.pec AS pec_organizzazione FROM persona p JOIN organizzazione o ON o.id = p.organizzazione_id WHERE p.organizzazione_id = 1 ORDER BY p.is_referente_acn DESC, p.cognome) TO 'acn_org1_02_referenti.csv' WITH CSV HEADER DELIMITER ';'

-- 03  Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
\copy (SELECT a.codice_inventario, a.nome AS nome_asset, ta.descrizione AS tipo_asset, ta.categoria_nis2 AS categoria_nis2_tipo, a.categoria AS categoria_asset, a.stato, a.ip_address AS indirizzo_ip, a.versione_sw AS versione_software, s.nome AS sede, s.citta, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, pr.ruolo_organizzativo AS ruolo_proprietario, COUNT(DISTINCT asv.servizio_id) AS n_servizi_supportati, STRING_AGG(DISTINCT sv.nome, ' | ') AS servizi_supportati, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche, TO_CHAR(a.created_at,'DD/MM/YYYY') AS data_inserimento, TO_CHAR(a.updated_at,'DD/MM/YYYY') AS ultimo_aggiornamento FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN asset_servizio asv ON asv.asset_id = a.id LEFT JOIN servizio sv ON sv.id = asv.servizio_id LEFT JOIN dipendenza d ON d.asset_id = a.id WHERE a.organizzazione_id = 1 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE GROUP BY a.codice_inventario, a.nome, ta.descrizione, ta.categoria_nis2, a.categoria, a.stato, a.ip_address, a.versione_sw, s.nome, s.citta, pr.cognome, pr.nome, pr.email, pr.ruolo_organizzativo, a.created_at, a.updated_at ORDER BY a.categoria, a.nome) TO 'acn_org1_03_asset_critici.csv' WITH CSV HEADER DELIMITER ';'

-- 04  Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
\copy (SELECT sv.nome AS nome_servizio, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, CASE WHEN sv.rto_ore <= 4 THEN 'Missione critica' WHEN sv.rto_ore <= 24 THEN 'Business critical' ELSE 'Standard' END AS classe_disponibilita, sv.url_servizio, COUNT(DISTINCT asv.asset_id) AS n_asset_supportanti, STRING_AGG(DISTINCT a.nome, ' | ') AS asset_supportanti, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche_fornitore FROM servizio sv LEFT JOIN asset_servizio asv ON asv.servizio_id = sv.id LEFT JOIN asset a ON a.id = asv.asset_id AND a.is_deleted = FALSE LEFT JOIN responsabilita r ON r.servizio_id = sv.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN dipendenza d ON d.servizio_id = sv.id WHERE sv.organizzazione_id = 1 AND sv.stato <> 'dismesso' GROUP BY sv.nome, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, sv.url_servizio, pr.cognome, pr.nome, pr.email ORDER BY sv.criticita, sv.nome) TO 'acn_org1_04_servizi.csv' WITH CSV HEADER DELIMITER ';'

-- 05  Dipendenze dalla catena di fornitura con contratto, SLA e stato
\copy (SELECT COALESCE(a.nome, sv.nome) AS risorsa, CASE WHEN d.asset_id IS NOT NULL THEN 'asset' ELSE 'servizio' END AS tipo_risorsa, COALESCE(a.categoria, sv.criticita) AS criticita_risorsa, f.nome AS fornitore, f.paese AS paese_fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico_nis2, d.tipo_dipendenza, d.criticita AS criticita_dipendenza, REPLACE(d.descrizione, U&'\2192', '->') AS descrizione, TO_CHAR(d.data_inizio,'DD/MM/YYYY') AS data_inizio_dipendenza, c.numero_contratto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS inizio_contratto, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS scadenza_contratto, CASE WHEN c.data_scadenza IS NULL THEN 'N/D' WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'In scadenza' ELSE 'Valido' END AS stato_contratto, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza_nis2, c.valore_annuo_eur FROM dipendenza d JOIN fornitore f ON f.id = d.fornitore_id LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id LEFT JOIN contratto c ON c.id = d.contratto_id WHERE d.organizzazione_id = 1 AND d.data_fine IS NULL ORDER BY d.criticita, f.nome) TO 'acn_org1_05_dipendenze.csv' WITH CSV HEADER DELIMITER ';'

-- 06  Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, TO_CHAR(ms.data_implementazione,'DD/MM/YYYY') AS data_implementazione, TO_CHAR(ms.data_verifica,'DD/MM/YYYY') AS prossima_verifica, CASE WHEN ms.asset_id IS NOT NULL THEN 'Asset: ' || a.nome WHEN ms.servizio_id IS NOT NULL THEN 'Servizio: ' || sv.nome ELSE 'Organizzazione' END AS ambito_applicazione, CASE ms.stato_implementazione WHEN 'implementata' THEN 'Verde' WHEN 'in_corso' THEN 'Giallo' WHEN 'pianificata' THEN 'Arancione' ELSE 'Grigio' END AS semaforo FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 1 ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org1_06_misure_sicurezza.csv' WITH CSV HEADER DELIMITER ';'

-- 07  Quadro riepilogativo: contatori chiave dell'organizzazione
\copy (SELECT o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='standard' AND a.is_deleted=FALSE) AS asset_standard, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_criticita, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='media' AND sv.stato='attivo') AS servizi_media_criticita, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=FALSE AND d.data_fine IS NULL) AS fornitori_standard, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='critica' AND d.data_fine IS NULL) AS dipendenze_critiche, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='alta' AND d.data_fine IS NULL) AS dipendenze_alte, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_in_scadenza_180gg, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza < CURRENT_DATE) AS contratti_scaduti, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') AS misure_implementate, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='in_corso') AS misure_in_corso, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='pianificata') AS misure_pianificate, (SELECT COUNT(DISTINCT a.id) FROM asset a JOIN responsabilita r ON r.asset_id=a.id WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE AND r.tipo_responsabilita='proprietario' AND r.data_fine IS NULL) AS asset_critici_con_proprietario, (SELECT MAX(pa.versione) FROM profilo_acn pa WHERE pa.organizzazione_id=o.id) AS versione_profilo_corrente, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo FROM organizzazione o WHERE o.id = 1) TO 'acn_org1_07_dashboard.csv' WITH CSV HEADER DELIMITER ';'

-- 08  Contratti scaduti o in scadenza entro 180 giorni, con priorita'
\copy (SELECT CASE WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '30 days' THEN 'URGENTE (entro 30gg)' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'CRITICO (entro 90gg)' ELSE 'ATTENZIONE (entro 180gg)' END AS priorita, f.nome AS fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico, c.numero_contratto, REPLACE(c.oggetto, U&'\2192', '->') AS oggetto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS data_inizio, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS data_scadenza, (c.data_scadenza - CURRENT_DATE) AS giorni_residui, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza, c.valore_annuo_eur, COUNT(d.id) AS n_dipendenze_associate, STRING_AGG(DISTINCT d.criticita, ', ') AS criticita_dipendenze, STRING_AGG(DISTINCT COALESCE(a.nome, sv.nome), ' | ') AS risorse_coinvolte FROM contratto c JOIN fornitore f ON f.id = c.fornitore_id LEFT JOIN dipendenza d ON d.contratto_id = c.id AND d.data_fine IS NULL LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id WHERE c.organizzazione_id = 1 AND (c.data_scadenza < CURRENT_DATE OR c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') GROUP BY c.id, f.nome, f.tipo, f.is_fornitore_critico, c.numero_contratto, c.oggetto, c.data_inizio, c.data_scadenza, c.sla_disponibilita, c.include_clausole_sicurezza, c.valore_annuo_eur ORDER BY c.data_scadenza) TO 'acn_org1_08_alert_scadenze.csv' WITH CSV HEADER DELIMITER ';'

-- 09  Asset critici/importanti privi di proprietario assegnato
\copy (SELECT 'GAP - Nessun proprietario' AS tipo_gap, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, a.categoria, a.stato, s.nome AS sede, s.citta, CASE WHEN EXISTS (SELECT 1 FROM responsabilita r2 WHERE r2.asset_id = a.id AND r2.data_fine IS NULL) THEN 'Ha altri ruoli assegnati' ELSE 'Nessun referente' END AS stato_copertura, TO_CHAR(a.created_at,'DD/MM/YYYY') AS inserito_il FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL WHERE a.organizzazione_id = 1 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE AND r.id IS NULL ORDER BY a.categoria, a.nome) TO 'acn_org1_09_gap_asset_senza_proprietario.csv' WITH CSV HEADER DELIMITER ';'

-- 10  Misure non ancora implementate (pianificate o in corso)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, CASE ms.stato_implementazione WHEN 'pianificata' THEN 'Da avviare' ELSE 'In avanzamento' END AS priorita_intervento, CASE WHEN ms.asset_id IS NOT NULL THEN a.nome WHEN ms.servizio_id IS NOT NULL THEN sv.nome ELSE 'Organizzazione intera' END AS ambito, CASE WHEN ms.asset_id IS NOT NULL THEN a.categoria WHEN ms.servizio_id IS NOT NULL THEN sv.criticita ELSE NULL END AS criticita_ambito FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 1 AND ms.stato_implementazione IN ('pianificata','in_corso') ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org1_10_gap_misure.csv' WITH CSV HEADER DELIMITER ';'

-- 11  Storico delle modifiche agli asset (audit trail)
\copy (SELECT TO_CHAR(ast.modificato_il,'DD/MM/YYYY HH24:MI') AS data_ora, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, ast.campo_modificato, ast.valore_precedente, ast.valore_nuovo, ast.modificato_da, COALESCE(REPLACE(ast.motivo, U&'\2192', '->'),'-') AS motivo FROM asset_storico ast JOIN asset a ON a.id = ast.asset_id JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod WHERE a.organizzazione_id = 1 ORDER BY ast.modificato_il DESC) TO 'acn_org1_11_storico_modifiche.csv' WITH CSV HEADER DELIMITER ';'

-- 12  Profilo target e profilo attuale per Subcategory (FNCSDP)
\copy (SELECT fs.funzione, fs.funzione_nome, a.subcategory_cod, fs.categoria_nome, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, a.livello_maturita, TO_CHAR(a.data_valutazione,'DD/MM/YYYY') AS data_valutazione FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 1 ORDER BY CASE fs.funzione WHEN 'GV' THEN 1 WHEN 'ID' THEN 2 WHEN 'PR' THEN 3 WHEN 'DE' THEN 4 WHEN 'RS' THEN 5 ELSE 6 END, a.subcategory_cod) TO 'acn_org1_12_profilo_target_attuale.csv' WITH CSV HEADER DELIMITER ';'

-- 13  Gap analysis: divario target/attuale ordinato per priorita'
\copy (SELECT fs.funzione, a.subcategory_cod, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, (a.livello_target - a.livello_attuale) AS gap, CASE WHEN a.livello_attuale >= a.livello_target THEN 'Raggiunto' ELSE 'Da colmare' END AS stato FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 1 ORDER BY CASE a.priorita WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END, (a.livello_target - a.livello_attuale) DESC, a.subcategory_cod) TO 'acn_org1_13_gap_analysis.csv' WITH CSV HEADER DELIMITER ';'


-- ============================================================
--  ORGANIZZAZIONE 2 :  BetaCloud S.r.l.  -  settore Infrastrutture digitali
-- ============================================================
\echo ''
\echo '>>> Export organizzazione 2 - BetaCloud S.r.l.'

-- 01  Anagrafica del soggetto NIS2 e referente ACN principale
\copy (SELECT o.nome AS organizzazione, o.codice_fiscale, o.settore_nis2, o.categoria_nis2, o.pec, o.sito_web, TO_CHAR(o.data_registrazione_acn,'DD/MM/YYYY') AS data_registrazione_acn, (pr.cognome || ' ' || pr.nome) AS referente_acn_principale, pr.email AS email_referente_acn, pr.telefono AS tel_referente_acn, pr.ruolo_organizzativo AS ruolo_referente_acn, CASE WHEN o.attiva THEN 'Attiva' ELSE 'Inattiva' END AS stato FROM organizzazione o LEFT JOIN persona pr ON pr.organizzazione_id = o.id AND pr.is_referente_acn = TRUE WHERE o.id = 2) TO 'acn_org2_01_anagrafica.csv' WITH CSV HEADER DELIMITER ';'

-- 02  Elenco dei referenti e contatti dell'organizzazione
\copy (SELECT (p.cognome || ' ' || p.nome) AS nominativo, p.email, p.telefono, p.ruolo_organizzativo AS ruolo, CASE WHEN p.is_referente_acn THEN 'Si' ELSE 'No' END AS referente_acn_ufficiale, o.nome AS organizzazione, o.pec AS pec_organizzazione FROM persona p JOIN organizzazione o ON o.id = p.organizzazione_id WHERE p.organizzazione_id = 2 ORDER BY p.is_referente_acn DESC, p.cognome) TO 'acn_org2_02_referenti.csv' WITH CSV HEADER DELIMITER ';'

-- 03  Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
\copy (SELECT a.codice_inventario, a.nome AS nome_asset, ta.descrizione AS tipo_asset, ta.categoria_nis2 AS categoria_nis2_tipo, a.categoria AS categoria_asset, a.stato, a.ip_address AS indirizzo_ip, a.versione_sw AS versione_software, s.nome AS sede, s.citta, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, pr.ruolo_organizzativo AS ruolo_proprietario, COUNT(DISTINCT asv.servizio_id) AS n_servizi_supportati, STRING_AGG(DISTINCT sv.nome, ' | ') AS servizi_supportati, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche, TO_CHAR(a.created_at,'DD/MM/YYYY') AS data_inserimento, TO_CHAR(a.updated_at,'DD/MM/YYYY') AS ultimo_aggiornamento FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN asset_servizio asv ON asv.asset_id = a.id LEFT JOIN servizio sv ON sv.id = asv.servizio_id LEFT JOIN dipendenza d ON d.asset_id = a.id WHERE a.organizzazione_id = 2 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE GROUP BY a.codice_inventario, a.nome, ta.descrizione, ta.categoria_nis2, a.categoria, a.stato, a.ip_address, a.versione_sw, s.nome, s.citta, pr.cognome, pr.nome, pr.email, pr.ruolo_organizzativo, a.created_at, a.updated_at ORDER BY a.categoria, a.nome) TO 'acn_org2_03_asset_critici.csv' WITH CSV HEADER DELIMITER ';'

-- 04  Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
\copy (SELECT sv.nome AS nome_servizio, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, CASE WHEN sv.rto_ore <= 4 THEN 'Missione critica' WHEN sv.rto_ore <= 24 THEN 'Business critical' ELSE 'Standard' END AS classe_disponibilita, sv.url_servizio, COUNT(DISTINCT asv.asset_id) AS n_asset_supportanti, STRING_AGG(DISTINCT a.nome, ' | ') AS asset_supportanti, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche_fornitore FROM servizio sv LEFT JOIN asset_servizio asv ON asv.servizio_id = sv.id LEFT JOIN asset a ON a.id = asv.asset_id AND a.is_deleted = FALSE LEFT JOIN responsabilita r ON r.servizio_id = sv.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN dipendenza d ON d.servizio_id = sv.id WHERE sv.organizzazione_id = 2 AND sv.stato <> 'dismesso' GROUP BY sv.nome, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, sv.url_servizio, pr.cognome, pr.nome, pr.email ORDER BY sv.criticita, sv.nome) TO 'acn_org2_04_servizi.csv' WITH CSV HEADER DELIMITER ';'

-- 05  Dipendenze dalla catena di fornitura con contratto, SLA e stato
\copy (SELECT COALESCE(a.nome, sv.nome) AS risorsa, CASE WHEN d.asset_id IS NOT NULL THEN 'asset' ELSE 'servizio' END AS tipo_risorsa, COALESCE(a.categoria, sv.criticita) AS criticita_risorsa, f.nome AS fornitore, f.paese AS paese_fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico_nis2, d.tipo_dipendenza, d.criticita AS criticita_dipendenza, REPLACE(d.descrizione, U&'\2192', '->') AS descrizione, TO_CHAR(d.data_inizio,'DD/MM/YYYY') AS data_inizio_dipendenza, c.numero_contratto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS inizio_contratto, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS scadenza_contratto, CASE WHEN c.data_scadenza IS NULL THEN 'N/D' WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'In scadenza' ELSE 'Valido' END AS stato_contratto, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza_nis2, c.valore_annuo_eur FROM dipendenza d JOIN fornitore f ON f.id = d.fornitore_id LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id LEFT JOIN contratto c ON c.id = d.contratto_id WHERE d.organizzazione_id = 2 AND d.data_fine IS NULL ORDER BY d.criticita, f.nome) TO 'acn_org2_05_dipendenze.csv' WITH CSV HEADER DELIMITER ';'

-- 06  Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, TO_CHAR(ms.data_implementazione,'DD/MM/YYYY') AS data_implementazione, TO_CHAR(ms.data_verifica,'DD/MM/YYYY') AS prossima_verifica, CASE WHEN ms.asset_id IS NOT NULL THEN 'Asset: ' || a.nome WHEN ms.servizio_id IS NOT NULL THEN 'Servizio: ' || sv.nome ELSE 'Organizzazione' END AS ambito_applicazione, CASE ms.stato_implementazione WHEN 'implementata' THEN 'Verde' WHEN 'in_corso' THEN 'Giallo' WHEN 'pianificata' THEN 'Arancione' ELSE 'Grigio' END AS semaforo FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 2 ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org2_06_misure_sicurezza.csv' WITH CSV HEADER DELIMITER ';'

-- 07  Quadro riepilogativo: contatori chiave dell'organizzazione
\copy (SELECT o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='standard' AND a.is_deleted=FALSE) AS asset_standard, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_criticita, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='media' AND sv.stato='attivo') AS servizi_media_criticita, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=FALSE AND d.data_fine IS NULL) AS fornitori_standard, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='critica' AND d.data_fine IS NULL) AS dipendenze_critiche, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='alta' AND d.data_fine IS NULL) AS dipendenze_alte, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_in_scadenza_180gg, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza < CURRENT_DATE) AS contratti_scaduti, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') AS misure_implementate, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='in_corso') AS misure_in_corso, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='pianificata') AS misure_pianificate, (SELECT COUNT(DISTINCT a.id) FROM asset a JOIN responsabilita r ON r.asset_id=a.id WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE AND r.tipo_responsabilita='proprietario' AND r.data_fine IS NULL) AS asset_critici_con_proprietario, (SELECT MAX(pa.versione) FROM profilo_acn pa WHERE pa.organizzazione_id=o.id) AS versione_profilo_corrente, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo FROM organizzazione o WHERE o.id = 2) TO 'acn_org2_07_dashboard.csv' WITH CSV HEADER DELIMITER ';'

-- 08  Contratti scaduti o in scadenza entro 180 giorni, con priorita'
\copy (SELECT CASE WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '30 days' THEN 'URGENTE (entro 30gg)' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'CRITICO (entro 90gg)' ELSE 'ATTENZIONE (entro 180gg)' END AS priorita, f.nome AS fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico, c.numero_contratto, REPLACE(c.oggetto, U&'\2192', '->') AS oggetto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS data_inizio, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS data_scadenza, (c.data_scadenza - CURRENT_DATE) AS giorni_residui, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza, c.valore_annuo_eur, COUNT(d.id) AS n_dipendenze_associate, STRING_AGG(DISTINCT d.criticita, ', ') AS criticita_dipendenze, STRING_AGG(DISTINCT COALESCE(a.nome, sv.nome), ' | ') AS risorse_coinvolte FROM contratto c JOIN fornitore f ON f.id = c.fornitore_id LEFT JOIN dipendenza d ON d.contratto_id = c.id AND d.data_fine IS NULL LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id WHERE c.organizzazione_id = 2 AND (c.data_scadenza < CURRENT_DATE OR c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') GROUP BY c.id, f.nome, f.tipo, f.is_fornitore_critico, c.numero_contratto, c.oggetto, c.data_inizio, c.data_scadenza, c.sla_disponibilita, c.include_clausole_sicurezza, c.valore_annuo_eur ORDER BY c.data_scadenza) TO 'acn_org2_08_alert_scadenze.csv' WITH CSV HEADER DELIMITER ';'

-- 09  Asset critici/importanti privi di proprietario assegnato
\copy (SELECT 'GAP - Nessun proprietario' AS tipo_gap, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, a.categoria, a.stato, s.nome AS sede, s.citta, CASE WHEN EXISTS (SELECT 1 FROM responsabilita r2 WHERE r2.asset_id = a.id AND r2.data_fine IS NULL) THEN 'Ha altri ruoli assegnati' ELSE 'Nessun referente' END AS stato_copertura, TO_CHAR(a.created_at,'DD/MM/YYYY') AS inserito_il FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL WHERE a.organizzazione_id = 2 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE AND r.id IS NULL ORDER BY a.categoria, a.nome) TO 'acn_org2_09_gap_asset_senza_proprietario.csv' WITH CSV HEADER DELIMITER ';'

-- 10  Misure non ancora implementate (pianificate o in corso)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, CASE ms.stato_implementazione WHEN 'pianificata' THEN 'Da avviare' ELSE 'In avanzamento' END AS priorita_intervento, CASE WHEN ms.asset_id IS NOT NULL THEN a.nome WHEN ms.servizio_id IS NOT NULL THEN sv.nome ELSE 'Organizzazione intera' END AS ambito, CASE WHEN ms.asset_id IS NOT NULL THEN a.categoria WHEN ms.servizio_id IS NOT NULL THEN sv.criticita ELSE NULL END AS criticita_ambito FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 2 AND ms.stato_implementazione IN ('pianificata','in_corso') ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org2_10_gap_misure.csv' WITH CSV HEADER DELIMITER ';'

-- 11  Storico delle modifiche agli asset (audit trail)
\copy (SELECT TO_CHAR(ast.modificato_il,'DD/MM/YYYY HH24:MI') AS data_ora, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, ast.campo_modificato, ast.valore_precedente, ast.valore_nuovo, ast.modificato_da, COALESCE(REPLACE(ast.motivo, U&'\2192', '->'),'-') AS motivo FROM asset_storico ast JOIN asset a ON a.id = ast.asset_id JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod WHERE a.organizzazione_id = 2 ORDER BY ast.modificato_il DESC) TO 'acn_org2_11_storico_modifiche.csv' WITH CSV HEADER DELIMITER ';'

-- 12  Profilo target e profilo attuale per Subcategory (FNCSDP)
\copy (SELECT fs.funzione, fs.funzione_nome, a.subcategory_cod, fs.categoria_nome, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, a.livello_maturita, TO_CHAR(a.data_valutazione,'DD/MM/YYYY') AS data_valutazione FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 2 ORDER BY CASE fs.funzione WHEN 'GV' THEN 1 WHEN 'ID' THEN 2 WHEN 'PR' THEN 3 WHEN 'DE' THEN 4 WHEN 'RS' THEN 5 ELSE 6 END, a.subcategory_cod) TO 'acn_org2_12_profilo_target_attuale.csv' WITH CSV HEADER DELIMITER ';'

-- 13  Gap analysis: divario target/attuale ordinato per priorita'
\copy (SELECT fs.funzione, a.subcategory_cod, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, (a.livello_target - a.livello_attuale) AS gap, CASE WHEN a.livello_attuale >= a.livello_target THEN 'Raggiunto' ELSE 'Da colmare' END AS stato FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 2 ORDER BY CASE a.priorita WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END, (a.livello_target - a.livello_attuale) DESC, a.subcategory_cod) TO 'acn_org2_13_gap_analysis.csv' WITH CSV HEADER DELIMITER ';'


-- ============================================================
--  ORGANIZZAZIONE 3 :  Ospedale Regionale Nord  -  settore Sanita'
-- ============================================================
\echo ''
\echo '>>> Export organizzazione 3 - Ospedale Regionale Nord'

-- 01  Anagrafica del soggetto NIS2 e referente ACN principale
\copy (SELECT o.nome AS organizzazione, o.codice_fiscale, o.settore_nis2, o.categoria_nis2, o.pec, o.sito_web, TO_CHAR(o.data_registrazione_acn,'DD/MM/YYYY') AS data_registrazione_acn, (pr.cognome || ' ' || pr.nome) AS referente_acn_principale, pr.email AS email_referente_acn, pr.telefono AS tel_referente_acn, pr.ruolo_organizzativo AS ruolo_referente_acn, CASE WHEN o.attiva THEN 'Attiva' ELSE 'Inattiva' END AS stato FROM organizzazione o LEFT JOIN persona pr ON pr.organizzazione_id = o.id AND pr.is_referente_acn = TRUE WHERE o.id = 3) TO 'acn_org3_01_anagrafica.csv' WITH CSV HEADER DELIMITER ';'

-- 02  Elenco dei referenti e contatti dell'organizzazione
\copy (SELECT (p.cognome || ' ' || p.nome) AS nominativo, p.email, p.telefono, p.ruolo_organizzativo AS ruolo, CASE WHEN p.is_referente_acn THEN 'Si' ELSE 'No' END AS referente_acn_ufficiale, o.nome AS organizzazione, o.pec AS pec_organizzazione FROM persona p JOIN organizzazione o ON o.id = p.organizzazione_id WHERE p.organizzazione_id = 3 ORDER BY p.is_referente_acn DESC, p.cognome) TO 'acn_org3_02_referenti.csv' WITH CSV HEADER DELIMITER ';'

-- 03  Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
\copy (SELECT a.codice_inventario, a.nome AS nome_asset, ta.descrizione AS tipo_asset, ta.categoria_nis2 AS categoria_nis2_tipo, a.categoria AS categoria_asset, a.stato, a.ip_address AS indirizzo_ip, a.versione_sw AS versione_software, s.nome AS sede, s.citta, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, pr.ruolo_organizzativo AS ruolo_proprietario, COUNT(DISTINCT asv.servizio_id) AS n_servizi_supportati, STRING_AGG(DISTINCT sv.nome, ' | ') AS servizi_supportati, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche, TO_CHAR(a.created_at,'DD/MM/YYYY') AS data_inserimento, TO_CHAR(a.updated_at,'DD/MM/YYYY') AS ultimo_aggiornamento FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN asset_servizio asv ON asv.asset_id = a.id LEFT JOIN servizio sv ON sv.id = asv.servizio_id LEFT JOIN dipendenza d ON d.asset_id = a.id WHERE a.organizzazione_id = 3 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE GROUP BY a.codice_inventario, a.nome, ta.descrizione, ta.categoria_nis2, a.categoria, a.stato, a.ip_address, a.versione_sw, s.nome, s.citta, pr.cognome, pr.nome, pr.email, pr.ruolo_organizzativo, a.created_at, a.updated_at ORDER BY a.categoria, a.nome) TO 'acn_org3_03_asset_critici.csv' WITH CSV HEADER DELIMITER ';'

-- 04  Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
\copy (SELECT sv.nome AS nome_servizio, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, CASE WHEN sv.rto_ore <= 4 THEN 'Missione critica' WHEN sv.rto_ore <= 24 THEN 'Business critical' ELSE 'Standard' END AS classe_disponibilita, sv.url_servizio, COUNT(DISTINCT asv.asset_id) AS n_asset_supportanti, STRING_AGG(DISTINCT a.nome, ' | ') AS asset_supportanti, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche_fornitore FROM servizio sv LEFT JOIN asset_servizio asv ON asv.servizio_id = sv.id LEFT JOIN asset a ON a.id = asv.asset_id AND a.is_deleted = FALSE LEFT JOIN responsabilita r ON r.servizio_id = sv.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN dipendenza d ON d.servizio_id = sv.id WHERE sv.organizzazione_id = 3 AND sv.stato <> 'dismesso' GROUP BY sv.nome, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, sv.url_servizio, pr.cognome, pr.nome, pr.email ORDER BY sv.criticita, sv.nome) TO 'acn_org3_04_servizi.csv' WITH CSV HEADER DELIMITER ';'

-- 05  Dipendenze dalla catena di fornitura con contratto, SLA e stato
\copy (SELECT COALESCE(a.nome, sv.nome) AS risorsa, CASE WHEN d.asset_id IS NOT NULL THEN 'asset' ELSE 'servizio' END AS tipo_risorsa, COALESCE(a.categoria, sv.criticita) AS criticita_risorsa, f.nome AS fornitore, f.paese AS paese_fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico_nis2, d.tipo_dipendenza, d.criticita AS criticita_dipendenza, REPLACE(d.descrizione, U&'\2192', '->') AS descrizione, TO_CHAR(d.data_inizio,'DD/MM/YYYY') AS data_inizio_dipendenza, c.numero_contratto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS inizio_contratto, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS scadenza_contratto, CASE WHEN c.data_scadenza IS NULL THEN 'N/D' WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'In scadenza' ELSE 'Valido' END AS stato_contratto, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza_nis2, c.valore_annuo_eur FROM dipendenza d JOIN fornitore f ON f.id = d.fornitore_id LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id LEFT JOIN contratto c ON c.id = d.contratto_id WHERE d.organizzazione_id = 3 AND d.data_fine IS NULL ORDER BY d.criticita, f.nome) TO 'acn_org3_05_dipendenze.csv' WITH CSV HEADER DELIMITER ';'

-- 06  Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, TO_CHAR(ms.data_implementazione,'DD/MM/YYYY') AS data_implementazione, TO_CHAR(ms.data_verifica,'DD/MM/YYYY') AS prossima_verifica, CASE WHEN ms.asset_id IS NOT NULL THEN 'Asset: ' || a.nome WHEN ms.servizio_id IS NOT NULL THEN 'Servizio: ' || sv.nome ELSE 'Organizzazione' END AS ambito_applicazione, CASE ms.stato_implementazione WHEN 'implementata' THEN 'Verde' WHEN 'in_corso' THEN 'Giallo' WHEN 'pianificata' THEN 'Arancione' ELSE 'Grigio' END AS semaforo FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 3 ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org3_06_misure_sicurezza.csv' WITH CSV HEADER DELIMITER ';'

-- 07  Quadro riepilogativo: contatori chiave dell'organizzazione
\copy (SELECT o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='standard' AND a.is_deleted=FALSE) AS asset_standard, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_criticita, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='media' AND sv.stato='attivo') AS servizi_media_criticita, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=FALSE AND d.data_fine IS NULL) AS fornitori_standard, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='critica' AND d.data_fine IS NULL) AS dipendenze_critiche, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='alta' AND d.data_fine IS NULL) AS dipendenze_alte, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_in_scadenza_180gg, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza < CURRENT_DATE) AS contratti_scaduti, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') AS misure_implementate, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='in_corso') AS misure_in_corso, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='pianificata') AS misure_pianificate, (SELECT COUNT(DISTINCT a.id) FROM asset a JOIN responsabilita r ON r.asset_id=a.id WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE AND r.tipo_responsabilita='proprietario' AND r.data_fine IS NULL) AS asset_critici_con_proprietario, (SELECT MAX(pa.versione) FROM profilo_acn pa WHERE pa.organizzazione_id=o.id) AS versione_profilo_corrente, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo FROM organizzazione o WHERE o.id = 3) TO 'acn_org3_07_dashboard.csv' WITH CSV HEADER DELIMITER ';'

-- 08  Contratti scaduti o in scadenza entro 180 giorni, con priorita'
\copy (SELECT CASE WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '30 days' THEN 'URGENTE (entro 30gg)' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'CRITICO (entro 90gg)' ELSE 'ATTENZIONE (entro 180gg)' END AS priorita, f.nome AS fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico, c.numero_contratto, REPLACE(c.oggetto, U&'\2192', '->') AS oggetto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS data_inizio, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS data_scadenza, (c.data_scadenza - CURRENT_DATE) AS giorni_residui, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza, c.valore_annuo_eur, COUNT(d.id) AS n_dipendenze_associate, STRING_AGG(DISTINCT d.criticita, ', ') AS criticita_dipendenze, STRING_AGG(DISTINCT COALESCE(a.nome, sv.nome), ' | ') AS risorse_coinvolte FROM contratto c JOIN fornitore f ON f.id = c.fornitore_id LEFT JOIN dipendenza d ON d.contratto_id = c.id AND d.data_fine IS NULL LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id WHERE c.organizzazione_id = 3 AND (c.data_scadenza < CURRENT_DATE OR c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') GROUP BY c.id, f.nome, f.tipo, f.is_fornitore_critico, c.numero_contratto, c.oggetto, c.data_inizio, c.data_scadenza, c.sla_disponibilita, c.include_clausole_sicurezza, c.valore_annuo_eur ORDER BY c.data_scadenza) TO 'acn_org3_08_alert_scadenze.csv' WITH CSV HEADER DELIMITER ';'

-- 09  Asset critici/importanti privi di proprietario assegnato
\copy (SELECT 'GAP - Nessun proprietario' AS tipo_gap, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, a.categoria, a.stato, s.nome AS sede, s.citta, CASE WHEN EXISTS (SELECT 1 FROM responsabilita r2 WHERE r2.asset_id = a.id AND r2.data_fine IS NULL) THEN 'Ha altri ruoli assegnati' ELSE 'Nessun referente' END AS stato_copertura, TO_CHAR(a.created_at,'DD/MM/YYYY') AS inserito_il FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL WHERE a.organizzazione_id = 3 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE AND r.id IS NULL ORDER BY a.categoria, a.nome) TO 'acn_org3_09_gap_asset_senza_proprietario.csv' WITH CSV HEADER DELIMITER ';'

-- 10  Misure non ancora implementate (pianificate o in corso)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, CASE ms.stato_implementazione WHEN 'pianificata' THEN 'Da avviare' ELSE 'In avanzamento' END AS priorita_intervento, CASE WHEN ms.asset_id IS NOT NULL THEN a.nome WHEN ms.servizio_id IS NOT NULL THEN sv.nome ELSE 'Organizzazione intera' END AS ambito, CASE WHEN ms.asset_id IS NOT NULL THEN a.categoria WHEN ms.servizio_id IS NOT NULL THEN sv.criticita ELSE NULL END AS criticita_ambito FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 3 AND ms.stato_implementazione IN ('pianificata','in_corso') ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org3_10_gap_misure.csv' WITH CSV HEADER DELIMITER ';'

-- 11  Storico delle modifiche agli asset (audit trail)
\copy (SELECT TO_CHAR(ast.modificato_il,'DD/MM/YYYY HH24:MI') AS data_ora, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, ast.campo_modificato, ast.valore_precedente, ast.valore_nuovo, ast.modificato_da, COALESCE(REPLACE(ast.motivo, U&'\2192', '->'),'-') AS motivo FROM asset_storico ast JOIN asset a ON a.id = ast.asset_id JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod WHERE a.organizzazione_id = 3 ORDER BY ast.modificato_il DESC) TO 'acn_org3_11_storico_modifiche.csv' WITH CSV HEADER DELIMITER ';'

-- 12  Profilo target e profilo attuale per Subcategory (FNCSDP)
\copy (SELECT fs.funzione, fs.funzione_nome, a.subcategory_cod, fs.categoria_nome, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, a.livello_maturita, TO_CHAR(a.data_valutazione,'DD/MM/YYYY') AS data_valutazione FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 3 ORDER BY CASE fs.funzione WHEN 'GV' THEN 1 WHEN 'ID' THEN 2 WHEN 'PR' THEN 3 WHEN 'DE' THEN 4 WHEN 'RS' THEN 5 ELSE 6 END, a.subcategory_cod) TO 'acn_org3_12_profilo_target_attuale.csv' WITH CSV HEADER DELIMITER ';'

-- 13  Gap analysis: divario target/attuale ordinato per priorita'
\copy (SELECT fs.funzione, a.subcategory_cod, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, (a.livello_target - a.livello_attuale) AS gap, CASE WHEN a.livello_attuale >= a.livello_target THEN 'Raggiunto' ELSE 'Da colmare' END AS stato FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 3 ORDER BY CASE a.priorita WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END, (a.livello_target - a.livello_attuale) DESC, a.subcategory_cod) TO 'acn_org3_13_gap_analysis.csv' WITH CSV HEADER DELIMITER ';'


-- ============================================================
--  ORGANIZZAZIONE 4 :  TransLogistica S.p.A.  -  settore Trasporti
-- ============================================================
\echo ''
\echo '>>> Export organizzazione 4 - TransLogistica S.p.A.'

-- 01  Anagrafica del soggetto NIS2 e referente ACN principale
\copy (SELECT o.nome AS organizzazione, o.codice_fiscale, o.settore_nis2, o.categoria_nis2, o.pec, o.sito_web, TO_CHAR(o.data_registrazione_acn,'DD/MM/YYYY') AS data_registrazione_acn, (pr.cognome || ' ' || pr.nome) AS referente_acn_principale, pr.email AS email_referente_acn, pr.telefono AS tel_referente_acn, pr.ruolo_organizzativo AS ruolo_referente_acn, CASE WHEN o.attiva THEN 'Attiva' ELSE 'Inattiva' END AS stato FROM organizzazione o LEFT JOIN persona pr ON pr.organizzazione_id = o.id AND pr.is_referente_acn = TRUE WHERE o.id = 4) TO 'acn_org4_01_anagrafica.csv' WITH CSV HEADER DELIMITER ';'

-- 02  Elenco dei referenti e contatti dell'organizzazione
\copy (SELECT (p.cognome || ' ' || p.nome) AS nominativo, p.email, p.telefono, p.ruolo_organizzativo AS ruolo, CASE WHEN p.is_referente_acn THEN 'Si' ELSE 'No' END AS referente_acn_ufficiale, o.nome AS organizzazione, o.pec AS pec_organizzazione FROM persona p JOIN organizzazione o ON o.id = p.organizzazione_id WHERE p.organizzazione_id = 4 ORDER BY p.is_referente_acn DESC, p.cognome) TO 'acn_org4_02_referenti.csv' WITH CSV HEADER DELIMITER ';'

-- 03  Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
\copy (SELECT a.codice_inventario, a.nome AS nome_asset, ta.descrizione AS tipo_asset, ta.categoria_nis2 AS categoria_nis2_tipo, a.categoria AS categoria_asset, a.stato, a.ip_address AS indirizzo_ip, a.versione_sw AS versione_software, s.nome AS sede, s.citta, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, pr.ruolo_organizzativo AS ruolo_proprietario, COUNT(DISTINCT asv.servizio_id) AS n_servizi_supportati, STRING_AGG(DISTINCT sv.nome, ' | ') AS servizi_supportati, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche, TO_CHAR(a.created_at,'DD/MM/YYYY') AS data_inserimento, TO_CHAR(a.updated_at,'DD/MM/YYYY') AS ultimo_aggiornamento FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN asset_servizio asv ON asv.asset_id = a.id LEFT JOIN servizio sv ON sv.id = asv.servizio_id LEFT JOIN dipendenza d ON d.asset_id = a.id WHERE a.organizzazione_id = 4 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE GROUP BY a.codice_inventario, a.nome, ta.descrizione, ta.categoria_nis2, a.categoria, a.stato, a.ip_address, a.versione_sw, s.nome, s.citta, pr.cognome, pr.nome, pr.email, pr.ruolo_organizzativo, a.created_at, a.updated_at ORDER BY a.categoria, a.nome) TO 'acn_org4_03_asset_critici.csv' WITH CSV HEADER DELIMITER ';'

-- 04  Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
\copy (SELECT sv.nome AS nome_servizio, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, CASE WHEN sv.rto_ore <= 4 THEN 'Missione critica' WHEN sv.rto_ore <= 24 THEN 'Business critical' ELSE 'Standard' END AS classe_disponibilita, sv.url_servizio, COUNT(DISTINCT asv.asset_id) AS n_asset_supportanti, STRING_AGG(DISTINCT a.nome, ' | ') AS asset_supportanti, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche_fornitore FROM servizio sv LEFT JOIN asset_servizio asv ON asv.servizio_id = sv.id LEFT JOIN asset a ON a.id = asv.asset_id AND a.is_deleted = FALSE LEFT JOIN responsabilita r ON r.servizio_id = sv.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN dipendenza d ON d.servizio_id = sv.id WHERE sv.organizzazione_id = 4 AND sv.stato <> 'dismesso' GROUP BY sv.nome, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, sv.url_servizio, pr.cognome, pr.nome, pr.email ORDER BY sv.criticita, sv.nome) TO 'acn_org4_04_servizi.csv' WITH CSV HEADER DELIMITER ';'

-- 05  Dipendenze dalla catena di fornitura con contratto, SLA e stato
\copy (SELECT COALESCE(a.nome, sv.nome) AS risorsa, CASE WHEN d.asset_id IS NOT NULL THEN 'asset' ELSE 'servizio' END AS tipo_risorsa, COALESCE(a.categoria, sv.criticita) AS criticita_risorsa, f.nome AS fornitore, f.paese AS paese_fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico_nis2, d.tipo_dipendenza, d.criticita AS criticita_dipendenza, REPLACE(d.descrizione, U&'\2192', '->') AS descrizione, TO_CHAR(d.data_inizio,'DD/MM/YYYY') AS data_inizio_dipendenza, c.numero_contratto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS inizio_contratto, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS scadenza_contratto, CASE WHEN c.data_scadenza IS NULL THEN 'N/D' WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'In scadenza' ELSE 'Valido' END AS stato_contratto, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza_nis2, c.valore_annuo_eur FROM dipendenza d JOIN fornitore f ON f.id = d.fornitore_id LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id LEFT JOIN contratto c ON c.id = d.contratto_id WHERE d.organizzazione_id = 4 AND d.data_fine IS NULL ORDER BY d.criticita, f.nome) TO 'acn_org4_05_dipendenze.csv' WITH CSV HEADER DELIMITER ';'

-- 06  Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, TO_CHAR(ms.data_implementazione,'DD/MM/YYYY') AS data_implementazione, TO_CHAR(ms.data_verifica,'DD/MM/YYYY') AS prossima_verifica, CASE WHEN ms.asset_id IS NOT NULL THEN 'Asset: ' || a.nome WHEN ms.servizio_id IS NOT NULL THEN 'Servizio: ' || sv.nome ELSE 'Organizzazione' END AS ambito_applicazione, CASE ms.stato_implementazione WHEN 'implementata' THEN 'Verde' WHEN 'in_corso' THEN 'Giallo' WHEN 'pianificata' THEN 'Arancione' ELSE 'Grigio' END AS semaforo FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 4 ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org4_06_misure_sicurezza.csv' WITH CSV HEADER DELIMITER ';'

-- 07  Quadro riepilogativo: contatori chiave dell'organizzazione
\copy (SELECT o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='standard' AND a.is_deleted=FALSE) AS asset_standard, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_criticita, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='media' AND sv.stato='attivo') AS servizi_media_criticita, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=FALSE AND d.data_fine IS NULL) AS fornitori_standard, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='critica' AND d.data_fine IS NULL) AS dipendenze_critiche, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='alta' AND d.data_fine IS NULL) AS dipendenze_alte, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_in_scadenza_180gg, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza < CURRENT_DATE) AS contratti_scaduti, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') AS misure_implementate, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='in_corso') AS misure_in_corso, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='pianificata') AS misure_pianificate, (SELECT COUNT(DISTINCT a.id) FROM asset a JOIN responsabilita r ON r.asset_id=a.id WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE AND r.tipo_responsabilita='proprietario' AND r.data_fine IS NULL) AS asset_critici_con_proprietario, (SELECT MAX(pa.versione) FROM profilo_acn pa WHERE pa.organizzazione_id=o.id) AS versione_profilo_corrente, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo FROM organizzazione o WHERE o.id = 4) TO 'acn_org4_07_dashboard.csv' WITH CSV HEADER DELIMITER ';'

-- 08  Contratti scaduti o in scadenza entro 180 giorni, con priorita'
\copy (SELECT CASE WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '30 days' THEN 'URGENTE (entro 30gg)' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'CRITICO (entro 90gg)' ELSE 'ATTENZIONE (entro 180gg)' END AS priorita, f.nome AS fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico, c.numero_contratto, REPLACE(c.oggetto, U&'\2192', '->') AS oggetto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS data_inizio, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS data_scadenza, (c.data_scadenza - CURRENT_DATE) AS giorni_residui, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza, c.valore_annuo_eur, COUNT(d.id) AS n_dipendenze_associate, STRING_AGG(DISTINCT d.criticita, ', ') AS criticita_dipendenze, STRING_AGG(DISTINCT COALESCE(a.nome, sv.nome), ' | ') AS risorse_coinvolte FROM contratto c JOIN fornitore f ON f.id = c.fornitore_id LEFT JOIN dipendenza d ON d.contratto_id = c.id AND d.data_fine IS NULL LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id WHERE c.organizzazione_id = 4 AND (c.data_scadenza < CURRENT_DATE OR c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') GROUP BY c.id, f.nome, f.tipo, f.is_fornitore_critico, c.numero_contratto, c.oggetto, c.data_inizio, c.data_scadenza, c.sla_disponibilita, c.include_clausole_sicurezza, c.valore_annuo_eur ORDER BY c.data_scadenza) TO 'acn_org4_08_alert_scadenze.csv' WITH CSV HEADER DELIMITER ';'

-- 09  Asset critici/importanti privi di proprietario assegnato
\copy (SELECT 'GAP - Nessun proprietario' AS tipo_gap, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, a.categoria, a.stato, s.nome AS sede, s.citta, CASE WHEN EXISTS (SELECT 1 FROM responsabilita r2 WHERE r2.asset_id = a.id AND r2.data_fine IS NULL) THEN 'Ha altri ruoli assegnati' ELSE 'Nessun referente' END AS stato_copertura, TO_CHAR(a.created_at,'DD/MM/YYYY') AS inserito_il FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL WHERE a.organizzazione_id = 4 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE AND r.id IS NULL ORDER BY a.categoria, a.nome) TO 'acn_org4_09_gap_asset_senza_proprietario.csv' WITH CSV HEADER DELIMITER ';'

-- 10  Misure non ancora implementate (pianificate o in corso)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, CASE ms.stato_implementazione WHEN 'pianificata' THEN 'Da avviare' ELSE 'In avanzamento' END AS priorita_intervento, CASE WHEN ms.asset_id IS NOT NULL THEN a.nome WHEN ms.servizio_id IS NOT NULL THEN sv.nome ELSE 'Organizzazione intera' END AS ambito, CASE WHEN ms.asset_id IS NOT NULL THEN a.categoria WHEN ms.servizio_id IS NOT NULL THEN sv.criticita ELSE NULL END AS criticita_ambito FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 4 AND ms.stato_implementazione IN ('pianificata','in_corso') ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org4_10_gap_misure.csv' WITH CSV HEADER DELIMITER ';'

-- 11  Storico delle modifiche agli asset (audit trail)
\copy (SELECT TO_CHAR(ast.modificato_il,'DD/MM/YYYY HH24:MI') AS data_ora, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, ast.campo_modificato, ast.valore_precedente, ast.valore_nuovo, ast.modificato_da, COALESCE(REPLACE(ast.motivo, U&'\2192', '->'),'-') AS motivo FROM asset_storico ast JOIN asset a ON a.id = ast.asset_id JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod WHERE a.organizzazione_id = 4 ORDER BY ast.modificato_il DESC) TO 'acn_org4_11_storico_modifiche.csv' WITH CSV HEADER DELIMITER ';'

-- 12  Profilo target e profilo attuale per Subcategory (FNCSDP)
\copy (SELECT fs.funzione, fs.funzione_nome, a.subcategory_cod, fs.categoria_nome, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, a.livello_maturita, TO_CHAR(a.data_valutazione,'DD/MM/YYYY') AS data_valutazione FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 4 ORDER BY CASE fs.funzione WHEN 'GV' THEN 1 WHEN 'ID' THEN 2 WHEN 'PR' THEN 3 WHEN 'DE' THEN 4 WHEN 'RS' THEN 5 ELSE 6 END, a.subcategory_cod) TO 'acn_org4_12_profilo_target_attuale.csv' WITH CSV HEADER DELIMITER ';'

-- 13  Gap analysis: divario target/attuale ordinato per priorita'
\copy (SELECT fs.funzione, a.subcategory_cod, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, (a.livello_target - a.livello_attuale) AS gap, CASE WHEN a.livello_attuale >= a.livello_target THEN 'Raggiunto' ELSE 'Da colmare' END AS stato FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 4 ORDER BY CASE a.priorita WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END, (a.livello_target - a.livello_attuale) DESC, a.subcategory_cod) TO 'acn_org4_13_gap_analysis.csv' WITH CSV HEADER DELIMITER ';'


-- ============================================================
--  ORGANIZZAZIONE 5 :  BancaMetro S.p.A.  -  settore Bancario
-- ============================================================
\echo ''
\echo '>>> Export organizzazione 5 - BancaMetro S.p.A.'

-- 01  Anagrafica del soggetto NIS2 e referente ACN principale
\copy (SELECT o.nome AS organizzazione, o.codice_fiscale, o.settore_nis2, o.categoria_nis2, o.pec, o.sito_web, TO_CHAR(o.data_registrazione_acn,'DD/MM/YYYY') AS data_registrazione_acn, (pr.cognome || ' ' || pr.nome) AS referente_acn_principale, pr.email AS email_referente_acn, pr.telefono AS tel_referente_acn, pr.ruolo_organizzativo AS ruolo_referente_acn, CASE WHEN o.attiva THEN 'Attiva' ELSE 'Inattiva' END AS stato FROM organizzazione o LEFT JOIN persona pr ON pr.organizzazione_id = o.id AND pr.is_referente_acn = TRUE WHERE o.id = 5) TO 'acn_org5_01_anagrafica.csv' WITH CSV HEADER DELIMITER ';'

-- 02  Elenco dei referenti e contatti dell'organizzazione
\copy (SELECT (p.cognome || ' ' || p.nome) AS nominativo, p.email, p.telefono, p.ruolo_organizzativo AS ruolo, CASE WHEN p.is_referente_acn THEN 'Si' ELSE 'No' END AS referente_acn_ufficiale, o.nome AS organizzazione, o.pec AS pec_organizzazione FROM persona p JOIN organizzazione o ON o.id = p.organizzazione_id WHERE p.organizzazione_id = 5 ORDER BY p.is_referente_acn DESC, p.cognome) TO 'acn_org5_02_referenti.csv' WITH CSV HEADER DELIMITER ';'

-- 03  Asset critici e importanti con proprietario, servizi supportati e n. dipendenze
\copy (SELECT a.codice_inventario, a.nome AS nome_asset, ta.descrizione AS tipo_asset, ta.categoria_nis2 AS categoria_nis2_tipo, a.categoria AS categoria_asset, a.stato, a.ip_address AS indirizzo_ip, a.versione_sw AS versione_software, s.nome AS sede, s.citta, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, pr.ruolo_organizzativo AS ruolo_proprietario, COUNT(DISTINCT asv.servizio_id) AS n_servizi_supportati, STRING_AGG(DISTINCT sv.nome, ' | ') AS servizi_supportati, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche, TO_CHAR(a.created_at,'DD/MM/YYYY') AS data_inserimento, TO_CHAR(a.updated_at,'DD/MM/YYYY') AS ultimo_aggiornamento FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN asset_servizio asv ON asv.asset_id = a.id LEFT JOIN servizio sv ON sv.id = asv.servizio_id LEFT JOIN dipendenza d ON d.asset_id = a.id WHERE a.organizzazione_id = 5 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE GROUP BY a.codice_inventario, a.nome, ta.descrizione, ta.categoria_nis2, a.categoria, a.stato, a.ip_address, a.versione_sw, s.nome, s.citta, pr.cognome, pr.nome, pr.email, pr.ruolo_organizzativo, a.created_at, a.updated_at ORDER BY a.categoria, a.nome) TO 'acn_org5_03_asset_critici.csv' WITH CSV HEADER DELIMITER ';'

-- 04  Servizi erogati con RTO/RPO, classe di disponibilita' e asset di supporto
\copy (SELECT sv.nome AS nome_servizio, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, CASE WHEN sv.rto_ore <= 4 THEN 'Missione critica' WHEN sv.rto_ore <= 24 THEN 'Business critical' ELSE 'Standard' END AS classe_disponibilita, sv.url_servizio, COUNT(DISTINCT asv.asset_id) AS n_asset_supportanti, STRING_AGG(DISTINCT a.nome, ' | ') AS asset_supportanti, (pr.cognome || ' ' || pr.nome) AS proprietario, pr.email AS email_proprietario, COUNT(DISTINCT d.id) FILTER (WHERE d.criticita IN ('critica','alta')) AS n_dipendenze_critiche_fornitore FROM servizio sv LEFT JOIN asset_servizio asv ON asv.servizio_id = sv.id LEFT JOIN asset a ON a.id = asv.asset_id AND a.is_deleted = FALSE LEFT JOIN responsabilita r ON r.servizio_id = sv.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL LEFT JOIN persona pr ON pr.id = r.persona_id LEFT JOIN dipendenza d ON d.servizio_id = sv.id WHERE sv.organizzazione_id = 5 AND sv.stato <> 'dismesso' GROUP BY sv.nome, sv.tipo_servizio, sv.criticita, sv.stato, sv.rto_ore, sv.rpo_ore, sv.url_servizio, pr.cognome, pr.nome, pr.email ORDER BY sv.criticita, sv.nome) TO 'acn_org5_04_servizi.csv' WITH CSV HEADER DELIMITER ';'

-- 05  Dipendenze dalla catena di fornitura con contratto, SLA e stato
\copy (SELECT COALESCE(a.nome, sv.nome) AS risorsa, CASE WHEN d.asset_id IS NOT NULL THEN 'asset' ELSE 'servizio' END AS tipo_risorsa, COALESCE(a.categoria, sv.criticita) AS criticita_risorsa, f.nome AS fornitore, f.paese AS paese_fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico_nis2, d.tipo_dipendenza, d.criticita AS criticita_dipendenza, REPLACE(d.descrizione, U&'\2192', '->') AS descrizione, TO_CHAR(d.data_inizio,'DD/MM/YYYY') AS data_inizio_dipendenza, c.numero_contratto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS inizio_contratto, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS scadenza_contratto, CASE WHEN c.data_scadenza IS NULL THEN 'N/D' WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'In scadenza' ELSE 'Valido' END AS stato_contratto, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza_nis2, c.valore_annuo_eur FROM dipendenza d JOIN fornitore f ON f.id = d.fornitore_id LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id LEFT JOIN contratto c ON c.id = d.contratto_id WHERE d.organizzazione_id = 5 AND d.data_fine IS NULL ORDER BY d.criticita, f.nome) TO 'acn_org5_05_dipendenze.csv' WITH CSV HEADER DELIMITER ';'

-- 06  Misure di sicurezza Art.21 NIS2 con stato di attuazione (semaforo)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, TO_CHAR(ms.data_implementazione,'DD/MM/YYYY') AS data_implementazione, TO_CHAR(ms.data_verifica,'DD/MM/YYYY') AS prossima_verifica, CASE WHEN ms.asset_id IS NOT NULL THEN 'Asset: ' || a.nome WHEN ms.servizio_id IS NOT NULL THEN 'Servizio: ' || sv.nome ELSE 'Organizzazione' END AS ambito_applicazione, CASE ms.stato_implementazione WHEN 'implementata' THEN 'Verde' WHEN 'in_corso' THEN 'Giallo' WHEN 'pianificata' THEN 'Arancione' ELSE 'Grigio' END AS semaforo FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 5 ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org5_06_misure_sicurezza.csv' WITH CSV HEADER DELIMITER ';'

-- 07  Quadro riepilogativo: contatori chiave dell'organizzazione
\copy (SELECT o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='standard' AND a.is_deleted=FALSE) AS asset_standard, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_criticita, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='media' AND sv.stato='attivo') AS servizi_media_criticita, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=FALSE AND d.data_fine IS NULL) AS fornitori_standard, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='critica' AND d.data_fine IS NULL) AS dipendenze_critiche, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita='alta' AND d.data_fine IS NULL) AS dipendenze_alte, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_in_scadenza_180gg, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza < CURRENT_DATE) AS contratti_scaduti, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') AS misure_implementate, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='in_corso') AS misure_in_corso, (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='pianificata') AS misure_pianificate, (SELECT COUNT(DISTINCT a.id) FROM asset a JOIN responsabilita r ON r.asset_id=a.id WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE AND r.tipo_responsabilita='proprietario' AND r.data_fine IS NULL) AS asset_critici_con_proprietario, (SELECT MAX(pa.versione) FROM profilo_acn pa WHERE pa.organizzazione_id=o.id) AS versione_profilo_corrente, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo FROM organizzazione o WHERE o.id = 5) TO 'acn_org5_07_dashboard.csv' WITH CSV HEADER DELIMITER ';'

-- 08  Contratti scaduti o in scadenza entro 180 giorni, con priorita'
\copy (SELECT CASE WHEN c.data_scadenza < CURRENT_DATE THEN 'SCADUTO' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '30 days' THEN 'URGENTE (entro 30gg)' WHEN c.data_scadenza <= CURRENT_DATE + INTERVAL '90 days' THEN 'CRITICO (entro 90gg)' ELSE 'ATTENZIONE (entro 180gg)' END AS priorita, f.nome AS fornitore, f.tipo AS tipo_fornitore, CASE WHEN f.is_fornitore_critico THEN 'Si' ELSE 'No' END AS fornitore_critico, c.numero_contratto, REPLACE(c.oggetto, U&'\2192', '->') AS oggetto, TO_CHAR(c.data_inizio,'DD/MM/YYYY') AS data_inizio, TO_CHAR(c.data_scadenza,'DD/MM/YYYY') AS data_scadenza, (c.data_scadenza - CURRENT_DATE) AS giorni_residui, c.sla_disponibilita AS sla_percent, CASE WHEN c.include_clausole_sicurezza THEN 'Si' ELSE 'No' END AS clausole_sicurezza, c.valore_annuo_eur, COUNT(d.id) AS n_dipendenze_associate, STRING_AGG(DISTINCT d.criticita, ', ') AS criticita_dipendenze, STRING_AGG(DISTINCT COALESCE(a.nome, sv.nome), ' | ') AS risorse_coinvolte FROM contratto c JOIN fornitore f ON f.id = c.fornitore_id LEFT JOIN dipendenza d ON d.contratto_id = c.id AND d.data_fine IS NULL LEFT JOIN asset a ON a.id = d.asset_id LEFT JOIN servizio sv ON sv.id = d.servizio_id WHERE c.organizzazione_id = 5 AND (c.data_scadenza < CURRENT_DATE OR c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') GROUP BY c.id, f.nome, f.tipo, f.is_fornitore_critico, c.numero_contratto, c.oggetto, c.data_inizio, c.data_scadenza, c.sla_disponibilita, c.include_clausole_sicurezza, c.valore_annuo_eur ORDER BY c.data_scadenza) TO 'acn_org5_08_alert_scadenze.csv' WITH CSV HEADER DELIMITER ';'

-- 09  Asset critici/importanti privi di proprietario assegnato
\copy (SELECT 'GAP - Nessun proprietario' AS tipo_gap, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, a.categoria, a.stato, s.nome AS sede, s.citta, CASE WHEN EXISTS (SELECT 1 FROM responsabilita r2 WHERE r2.asset_id = a.id AND r2.data_fine IS NULL) THEN 'Ha altri ruoli assegnati' ELSE 'Nessun referente' END AS stato_copertura, TO_CHAR(a.created_at,'DD/MM/YYYY') AS inserito_il FROM asset a JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod LEFT JOIN sede s ON s.id = a.sede_id LEFT JOIN responsabilita r ON r.asset_id = a.id AND r.tipo_responsabilita = 'proprietario' AND r.data_fine IS NULL WHERE a.organizzazione_id = 5 AND a.categoria IN ('critico','importante') AND a.stato <> 'dismesso' AND a.is_deleted = FALSE AND r.id IS NULL ORDER BY a.categoria, a.nome) TO 'acn_org5_09_gap_asset_senza_proprietario.csv' WITH CSV HEADER DELIMITER ';'

-- 10  Misure non ancora implementate (pianificate o in corso)
\copy (SELECT ms.articolo_nis2 AS riferimento_normativo, ms.categoria, ms.nome AS misura, ms.stato_implementazione, CASE ms.stato_implementazione WHEN 'pianificata' THEN 'Da avviare' ELSE 'In avanzamento' END AS priorita_intervento, CASE WHEN ms.asset_id IS NOT NULL THEN a.nome WHEN ms.servizio_id IS NOT NULL THEN sv.nome ELSE 'Organizzazione intera' END AS ambito, CASE WHEN ms.asset_id IS NOT NULL THEN a.categoria WHEN ms.servizio_id IS NOT NULL THEN sv.criticita ELSE NULL END AS criticita_ambito FROM misura_sicurezza ms LEFT JOIN asset a ON a.id = ms.asset_id LEFT JOIN servizio sv ON sv.id = ms.servizio_id WHERE ms.organizzazione_id = 5 AND ms.stato_implementazione IN ('pianificata','in_corso') ORDER BY ms.stato_implementazione, ms.categoria) TO 'acn_org5_10_gap_misure.csv' WITH CSV HEADER DELIMITER ';'

-- 11  Storico delle modifiche agli asset (audit trail)
\copy (SELECT TO_CHAR(ast.modificato_il,'DD/MM/YYYY HH24:MI') AS data_ora, a.codice_inventario, a.nome AS asset, ta.descrizione AS tipo_asset, ast.campo_modificato, ast.valore_precedente, ast.valore_nuovo, ast.modificato_da, COALESCE(REPLACE(ast.motivo, U&'\2192', '->'),'-') AS motivo FROM asset_storico ast JOIN asset a ON a.id = ast.asset_id JOIN tipo_asset ta ON ta.codice = a.tipo_asset_cod WHERE a.organizzazione_id = 5 ORDER BY ast.modificato_il DESC) TO 'acn_org5_11_storico_modifiche.csv' WITH CSV HEADER DELIMITER ';'

-- 12  Profilo target e profilo attuale per Subcategory (FNCSDP)
\copy (SELECT fs.funzione, fs.funzione_nome, a.subcategory_cod, fs.categoria_nome, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, a.livello_maturita, TO_CHAR(a.data_valutazione,'DD/MM/YYYY') AS data_valutazione FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 5 ORDER BY CASE fs.funzione WHEN 'GV' THEN 1 WHEN 'ID' THEN 2 WHEN 'PR' THEN 3 WHEN 'DE' THEN 4 WHEN 'RS' THEN 5 ELSE 6 END, a.subcategory_cod) TO 'acn_org5_12_profilo_target_attuale.csv' WITH CSV HEADER DELIMITER ';'

-- 13  Gap analysis: divario target/attuale ordinato per priorita'
\copy (SELECT fs.funzione, a.subcategory_cod, fs.descrizione, a.priorita, a.livello_target, a.livello_attuale, (a.livello_target - a.livello_attuale) AS gap, CASE WHEN a.livello_attuale >= a.livello_target THEN 'Raggiunto' ELSE 'Da colmare' END AS stato FROM assessment a JOIN framework_subcategory fs ON fs.codice = a.subcategory_cod WHERE a.organizzazione_id = 5 ORDER BY CASE a.priorita WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END, (a.livello_target - a.livello_attuale) DESC, a.subcategory_cod) TO 'acn_org5_13_gap_analysis.csv' WITH CSV HEADER DELIMITER ';'


-- ============================================================
--  RIEPILOGO MULTI-ORGANIZZAZIONE (tutte le org in un unico file)
-- ============================================================
\echo ''
\echo '>>> Export dashboard multi-organizzazione'

-- Confronto sintetico tra tutte le organizzazioni registrate
\copy (SELECT o.id AS org_id, o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='critico' AND a.is_deleted=FALSE) AS asset_critici, (SELECT COUNT(*) FROM asset a WHERE a.organizzazione_id=o.id AND a.categoria='importante' AND a.is_deleted=FALSE) AS asset_importanti, (SELECT COUNT(*) FROM servizio sv WHERE sv.organizzazione_id=o.id AND sv.criticita='alta' AND sv.stato='attivo') AS servizi_alta_crit, (SELECT COUNT(*) FROM dipendenza d WHERE d.organizzazione_id=o.id AND d.criticita IN ('critica','alta') AND d.data_fine IS NULL) AS dip_critiche, (SELECT COUNT(DISTINCT d.fornitore_id) FROM dipendenza d JOIN fornitore f ON f.id=d.fornitore_id WHERE d.organizzazione_id=o.id AND f.is_fornitore_critico=TRUE AND d.data_fine IS NULL) AS fornitori_critici, ROUND(100.0 * (SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id AND ms.stato_implementazione='implementata') / NULLIF((SELECT COUNT(*) FROM misura_sicurezza ms WHERE ms.organizzazione_id=o.id),0), 1) AS perc_misure_implementate, (SELECT COUNT(*) FROM contratto c WHERE c.organizzazione_id=o.id AND c.data_scadenza >= CURRENT_DATE AND c.data_scadenza <= CURRENT_DATE + INTERVAL '180 days') AS contratti_scadenza_180gg, (SELECT pa.stato FROM profilo_acn pa WHERE pa.organizzazione_id=o.id ORDER BY pa.versione DESC LIMIT 1) AS stato_profilo, (SELECT p.email FROM persona p WHERE p.organizzazione_id=o.id AND p.is_referente_acn=TRUE LIMIT 1) AS email_referente_acn FROM organizzazione o ORDER BY o.categoria_nis2, o.settore_nis2, o.nome) TO 'acn_dashboard_multiorg.csv' WITH CSV HEADER DELIMITER ';'

-- Sintesi dei gap per tutte le organizzazioni (completamento del profilo)
\copy (SELECT o.id AS org_id, o.nome AS organizzazione, o.settore_nis2, o.categoria_nis2, COUNT(*) AS subcategory_valutate, COUNT(*) FILTER (WHERE a.livello_attuale >= a.livello_target) AS raggiunte, COUNT(*) FILTER (WHERE a.livello_attuale < a.livello_target) AS da_colmare, COUNT(*) FILTER (WHERE a.livello_attuale < a.livello_target AND a.priorita='alta') AS gap_priorita_alta, ROUND(AVG(a.livello_target - a.livello_attuale), 2) AS gap_medio, ROUND(100.0 * SUM(a.livello_attuale) / NULLIF(SUM(a.livello_target),0), 1) AS completamento_perc FROM assessment a JOIN organizzazione o ON o.id = a.organizzazione_id GROUP BY o.id, o.nome, o.settore_nis2, o.categoria_nis2 ORDER BY completamento_perc DESC) TO 'acn_gap_dashboard_multiorg.csv' WITH CSV HEADER DELIMITER ';'

\echo ''
\echo 'Export completato: 67 file CSV generati nella cartella corrente.'
